version: '3.8'

services:
  postgres:
    container_name: db_zoc_api
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - db_zoc_api:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zoc
      - POSTGRES_PASSWORD=zoc
      - POSTGRES_DB=zoc_api

volumes:
  db_zoc_api:
